#!/bin/sh

### BEGIN INIT INFO
# Provides:             baylorbot
# Required-Start:
# Required-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    BaylorBot gets sports information and updates the sidebar of /r/baylorsports
### END INIT INFO

export PATH=$PATH:/opt/node/bin
export NODE_PATH=$NODE_PATH:/opt/node/lib/node_modules
export HOME=/root

case "$1" in
  start)
    forever -p /root/.forever --sourceDir=/home/pi/BaylorBot/main.js
    ;;
  stop)
    exec forever stop /home/pi/BaylorBot/main.js
    ;;
  restart)
    exec forever restart /home/pi/BaylorBot/main.js
    ;;
  *)

  echo "Usage: /etc/init.d/baylorbot {start|stop|restart}"
  exit 1
  ;;
esac
exit 0
